### ISSUE TITLE
bug: PATCH /gardens does not always trigger search index update when publishing

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden-backend#140]
(sometimes?) when I publish a garden from the frontend, the search index does not reflect the fact that it's been published, though the frontend shows the "published" icon, the DB entry has the correct value of `doi_is_draft = false`, and there's no lingering entry in the `failed_search_index_updates` table. 

So far we've only seen this when the changes in question are switching the draft status of a DOI, but we should see if we can reproduce with updates to other metadata in case it's a bug in the DOI logic. 

TODO: 
 - [ ] diagnose the actual bug, which isn't obvious from a cursory look at the route logic or logs
     - this may be a good opportunity to work on improving our logging infra from the lightsail defaults
 - [ ] fix the bug 
 - [ ] come up with a strategy for catching cases like this in the future where the SI falls out of sync with the DB

**Comment by hholb** [comment]
Resolved in #155
