### ISSUE TITLE
Globus Search Index Ingest backend route

### ISSUE THREAD

**Issue by ericblau** [Garden-AI/garden-backend#15]
The Garden client currently is writing directly to the Globus Search Index, which requires every Garden user to have write permissions.  

Task:  implement a route on the Garden backend that writes to the Garden search index.
It can be based on https://github.com/Garden-AI/globus-search-writer-lambda (which is actually in use for DLHub, but lives in the Garden-AI github.)  However, since routes in the Garden backend app are already authorized by Globus Auth, this backend route might be simpler, depending on how much policy we want to implement.

**Comment by isaac-darling** [comment]
Closed by #22
