### ISSUE TITLE
Productionized full-text search in Postgres

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden-backend#161]
Hayden showed that we can plausibly replace the search index with Postgres in https://github.com/Garden-AI/garden-backend/issues/154. This ticket will track the work of taking the new search endpoint from prototype to prod deployment.

Things to consider:
- I'd like to be confident that this solution can support on the order of 1k gardens.
- Do we need to add any indexing upfront?

**Comment by shane-jung** [comment]
Just waiting for one change on backend (adding support for sorting), at which point I'll add the corresponding changes on the frontend and mark my PR as ready
